"""The bibliography for the examples and the design document.

Each entry: key -> (in-text label, full reference in Markdown). Every entry was
checked against the publisher or arXiv record. Cite in notebook Markdown as
[@key] (parenthetical) or [@key1; @key2]; the builder resolves them and
appends a References cell.
"""

REFERENCES = {
    "anderson1999": ("Anderson & Anderson, 1999",
        "Anderson, J. L. & Anderson, S. L. (1999). A Monte Carlo implementation of the nonlinear filtering problem to produce ensemble assimilations and forecasts. *Monthly Weather Review*, 127(12), 2741–2758."),
    "anderson2001": ("Anderson, 2001",
        "Anderson, J. L. (2001). An ensemble adjustment Kalman filter for data assimilation. *Monthly Weather Review*, 129(12), 2884–2903."),
    "bishop2001": ("Bishop, Etherton & Majumdar, 2001",
        "Bishop, C. H., Etherton, B. J. & Majumdar, S. J. (2001). Adaptive sampling with the ensemble transform Kalman filter. Part I: Theoretical aspects. *Monthly Weather Review*, 129(3), 420–436."),
    "bocquet2014": ("Bocquet & Sakov, 2014",
        "Bocquet, M. & Sakov, P. (2014). An iterative ensemble Kalman smoother. *Quarterly Journal of the Royal Meteorological Society*, 140(682), 1521–1535."),
    "botha2023": ("Botha et al., 2023",
        "Botha, I., Adams, M. P., Tran, D. K., Bennett, F. R. & Drovandi, C. (2023). Component-wise iterative ensemble Kalman inversion for static Bayesian models with unknown measurement error covariance. *Inverse Problems*, 39(12), 125014."),
    "burgers1998": ("Burgers, van Leeuwen & Evensen, 1998",
        "Burgers, G., van Leeuwen, P. J. & Evensen, G. (1998). Analysis scheme in the ensemble Kalman filter. *Monthly Weather Review*, 126(6), 1719–1724."),
    "carrassi2017": ("Carrassi et al., 2017",
        "Carrassi, A., Bocquet, M., Hannart, A. & Ghil, M. (2017). Estimating model evidence using data assimilation. *Quarterly Journal of the Royal Meteorological Society*, 143(703), 866–880."),
    "chaloner1995": ("Chaloner & Verdinelli, 1995",
        "Chaloner, K. & Verdinelli, I. (1995). Bayesian experimental design: a review. *Statistical Science*, 10(3), 273–304."),
    "chen2013": ("Chen & Oliver, 2013",
        "Chen, Y. & Oliver, D. S. (2013). Levenberg–Marquardt forms of the iterative ensemble smoother for efficient history matching and uncertainty quantification. *Computational Geosciences*, 17(4), 689–703."),
    "chen2022": ("Chen, Sanz-Alonso & Willett, 2022",
        "Chen, Y., Sanz-Alonso, D. & Willett, R. (2022). Autodifferentiable ensemble Kalman filters. *SIAM Journal on Mathematics of Data Science*, 4(2), 801–833."),
    "emerick2013": ("Emerick & Reynolds, 2013",
        "Emerick, A. A. & Reynolds, A. C. (2013). Ensemble smoother with multiple data assimilation. *Computers & Geosciences*, 55, 3–15."),
    "ernst2015": ("Ernst, Sprungk & Starkloff, 2015",
        "Ernst, O. G., Sprungk, B. & Starkloff, H.-J. (2015). Analysis of the ensemble and polynomial chaos Kalman filters in Bayesian inverse problems. *SIAM/ASA Journal on Uncertainty Quantification*, 3(1), 823–851."),
    "evensen1994": ("Evensen, 1994",
        "Evensen, G. (1994). Sequential data assimilation with a nonlinear quasi-geostrophic model using Monte Carlo methods to forecast error statistics. *Journal of Geophysical Research: Oceans*, 99(C5), 10143–10162."),
    "evensen2000": ("Evensen & van Leeuwen, 2000",
        "Evensen, G. & van Leeuwen, P. J. (2000). An ensemble Kalman smoother for nonlinear dynamics. *Monthly Weather Review*, 128(6), 1852–1867."),
    "evensen2009": ("Evensen, 2009",
        "Evensen, G. (2009). The ensemble Kalman filter for combined state and parameter estimation. *IEEE Control Systems Magazine*, 29(3), 83–104."),
    "garbuno2020aldi": ("Garbuno-Inigo, Nüsken & Reich, 2020",
        "Garbuno-Inigo, A., Nüsken, N. & Reich, S. (2020). Affine invariant interacting Langevin dynamics for Bayesian inference. *SIAM Journal on Applied Dynamical Systems*, 19(3), 1633–1658."),
    "garbuno2020eks": ("Garbuno-Inigo et al., 2020",
        "Garbuno-Inigo, A., Hoffmann, F., Li, W. & Stuart, A. M. (2020). Interacting Langevin diffusions: gradient structure and ensemble Kalman sampler. *SIAM Journal on Applied Dynamical Systems*, 19(1), 412–441."),
    "gaspari1999": ("Gaspari & Cohn, 1999",
        "Gaspari, G. & Cohn, S. E. (1999). Construction of correlation functions in two and three dimensions. *Quarterly Journal of the Royal Meteorological Society*, 125(554), 723–757."),
    "gelman2013": ("Gelman et al., 2013",
        "Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A. & Rubin, D. B. (2013). *Bayesian Data Analysis* (3rd ed.). CRC Press."),
    "hamill2000": ("Hamill & Snyder, 2000",
        "Hamill, T. M. & Snyder, C. (2000). A hybrid ensemble Kalman filter–3D variational analysis scheme. *Monthly Weather Review*, 128(8), 2905–2919."),
    "hesterberg1995": ("Hesterberg, 1995",
        "Hesterberg, T. (1995). Weighted average importance sampling and defensive mixture distributions. *Technometrics*, 37(2), 185–194."),
    "higham2008": ("Higham, 2008",
        "Higham, N. J. (2008). *Functions of Matrices: Theory and Computation*. SIAM."),
    "hamill2001": ("Hamill, Whitaker & Snyder, 2001",
        "Hamill, T. M., Whitaker, J. S. & Snyder, C. (2001). Distance-dependent filtering of background error covariance estimates in an ensemble Kalman filter. *Monthly Weather Review*, 129(11), 2776–2790."),
    "houtekamer2001": ("Houtekamer & Mitchell, 2001",
        "Houtekamer, P. L. & Mitchell, H. L. (2001). A sequential ensemble Kalman filter for atmospheric data assimilation. *Monthly Weather Review*, 129(1), 123–137."),
    "wang2004": ("Wang, Bishop & Julier, 2004",
        "Wang, X., Bishop, C. H. & Julier, S. J. (2004). Which is better, an ensemble of positive–negative pairs or a centered spherical simplex ensemble? *Monthly Weather Review*, 132(7), 1590–1605."),
    "houtekamer1998": ("Houtekamer & Mitchell, 1998",
        "Houtekamer, P. L. & Mitchell, H. L. (1998). Data assimilation using an ensemble Kalman filter technique. *Monthly Weather Review*, 126(3), 796–811."),
    "huang2022": ("Huang, Schneider & Stuart, 2022",
        "Huang, D. Z., Schneider, T. & Stuart, A. M. (2022). Iterated Kalman methodology for inverse problems. *Journal of Computational Physics*, 463, 111262."),
    "hunt2007": ("Hunt, Kostelich & Szunyogh, 2007",
        "Hunt, B. R., Kostelich, E. J. & Szunyogh, I. (2007). Efficient data assimilation for spatiotemporal chaos: a local ensemble transform Kalman filter. *Physica D*, 230(1–2), 112–126."),
    "iglesias2013": ("Iglesias, Law & Stuart, 2013",
        "Iglesias, M. A., Law, K. J. H. & Stuart, A. M. (2013). Ensemble Kalman methods for inverse problems. *Inverse Problems*, 29(4), 045001."),
    "iglesias2016": ("Iglesias, 2016",
        "Iglesias, M. A. (2016). A regularizing iterative ensemble Kalman method for PDE-constrained inverse problems. *Inverse Problems*, 32(2), 025002."),
    "iglesias2021": ("Iglesias & Yang, 2021",
        "Iglesias, M. & Yang, Y. (2021). Adaptive regularisation for ensemble Kalman inversion. *Inverse Problems*, 37(2), 025008."),
    "jasra2011": ("Jasra et al., 2011",
        "Jasra, A., Stephens, D. A., Doucet, A. & Tsagaris, T. (2011). Inference for Lévy-driven stochastic volatility models via adaptive sequential Monte Carlo. *Scandinavian Journal of Statistics*, 38(1), 1–22."),
    "journel1978": ("Journel & Huijbregts, 1978",
        "Journel, A. G. & Huijbregts, C. J. (1978). *Mining Geostatistics*. Academic Press."),
    "kalman1960": ("Kalman, 1960",
        "Kalman, R. E. (1960). A new approach to linear filtering and prediction problems. *Journal of Basic Engineering*, 82(1), 35–45."),
    "kitagawa1996": ("Kitagawa, 1996",
        "Kitagawa, G. (1996). Monte Carlo filter and smoother for non-Gaussian nonlinear state space models. *Journal of Computational and Graphical Statistics*, 5(1), 1–25."),
    "kong1994": ("Kong, Liu & Wong, 1994",
        "Kong, A., Liu, J. S. & Wong, W. H. (1994). Sequential imputations and Bayesian missing data problems. *Journal of the American Statistical Association*, 89(425), 278–288."),
    "lorenz1996": ("Lorenz, 1996",
        "Lorenz, E. N. (1996). Predictability: a problem partly solved. In *Proceedings of the ECMWF Seminar on Predictability*, vol. 1, 1–18. Reading, UK."),
    "marzouk2016": ("Marzouk et al., 2016",
        "Marzouk, Y., Moselhy, T., Parno, M. & Spantini, A. (2016). Sampling via measure transport: an introduction. In *Handbook of Uncertainty Quantification*. Springer."),
    "ott2004": ("Ott et al., 2004",
        "Ott, E., Hunt, B. R., Szunyogh, I., Zimin, A. V., Kostelich, E. J., Corazza, M., Kalnay, E., Patil, D. J. & Yorke, J. A. (2004). A local ensemble Kalman filter for atmospheric data assimilation. *Tellus A*, 56(5), 415–428."),
    "pham2001": ("Pham, 2001",
        "Pham, D. T. (2001). Stochastic methods for sequential data assimilation in strongly nonlinear systems. *Monthly Weather Review*, 129(5), 1194–1207."),
    "rasmussen2006": ("Rasmussen & Williams, 2006",
        "Rasmussen, C. E. & Williams, C. K. I. (2006). *Gaussian Processes for Machine Learning*. MIT Press."),
    "sakov2008": ("Sakov & Oke, 2008",
        "Sakov, P. & Oke, P. R. (2008). A deterministic formulation of the ensemble Kalman filter: an alternative to ensemble square root filters. *Tellus A*, 60(2), 361–371."),
    "sakov2011": ("Sakov & Bertino, 2011",
        "Sakov, P. & Bertino, L. (2011). Relation between two common localisation methods for the EnKF. *Computational Geosciences*, 15(2), 225–237."),
    "spantini2022": ("Spantini, Baptista & Marzouk, 2022",
        "Spantini, A., Baptista, R. & Marzouk, Y. (2022). Coupling techniques for nonlinear ensemble filtering. *SIAM Review*, 64(4), 921–953."),
    "tippett2003": ("Tippett et al., 2003",
        "Tippett, M. K., Anderson, J. L., Bishop, C. H., Hamill, T. M. & Whitaker, J. S. (2003). Ensemble square root filters. *Monthly Weather Review*, 131(7), 1485–1490."),
    "whitaker2002": ("Whitaker & Hamill, 2002",
        "Whitaker, J. S. & Hamill, T. M. (2002). Ensemble data assimilation without perturbed observations. *Monthly Weather Review*, 130(7), 1913–1924."),
    "whitaker2012": ("Whitaker & Hamill, 2012",
        "Whitaker, J. S. & Hamill, T. M. (2012). Evaluating methods to account for system errors in ensemble data assimilation. *Monthly Weather Review*, 140(9), 3078–3089."),
    "wilson2021": ("Wilson et al., 2021",
        "Wilson, J. T., Borovitskiy, V., Terenin, A., Mostowsky, P. & Deisenroth, M. P. (2021). Pathwise conditioning of Gaussian processes. *Journal of Machine Learning Research*, 22(105), 1–47."),
    "zhang2004": ("Zhang, Snyder & Sun, 2004",
        "Zhang, F., Snyder, C. & Sun, J. (2004). Impacts of initial estimate and observation availability on convective-scale data assimilation with an ensemble Kalman filter. *Monthly Weather Review*, 132(5), 1238–1253."),
}
